**What you will learn**
* Extracting, filtering, and transforming data from DataFrames
* Advanced indexing with multiple levels
* Tidying, rearranging and restructuring your data
* Pivoting, melting, and stacking DataFrames
* Identifying and spliting DataFrames by groups

In [2]:
import pandas as pd

In [3]:
from numpy.matrixlib import defmatrix
from google.colab import files
uploaded = files.upload()
data = pd.read_csv("data_nan.csv", index_col='month')

Saving data_nan.csv to data_nan.csv

In [4]:
data

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

In [5]:
print(data)

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

In [6]:
data['eggs']

month
Jan     47
Feb    110
Mar    221
Apr     77
May    132
Jun    205
Name: eggs, dtype: int64

In [7]:
data['salt']['May']

nan

In [8]:
data.loc['May', 'spam']

52

In [9]:
data.iloc[4, 2]

52

In [10]:
data_new = data[['salt','eggs']]
data_new

       salt  eggs
month
Jan    12.0    47
Feb    50.0   110
Mar    89.0   221
Apr    87.0    77
May     NaN   132
Jun    60.0   205

In [11]:
data.loc[:, 'eggs':'salt']

       eggs  salt
month
Jan      47  12.0
Feb     110  50.0
Mar     221  89.0
Apr      77  87.0
May     132   NaN
Jun     205  60.0

In [12]:
data.loc['Jan':'Apr',:]

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20

In [13]:
data.loc['Mar':'May', 'salt':'spam']

       salt  spam
month
Mar    89.0    72
Apr    87.0    20
May     NaN    52

In [14]:
data.iloc[2:5, 1:]

       salt  spam
month
Mar    89.0    72
Apr    87.0    20
May     NaN    52

**Using lists rather than slices**

In [15]:
data.loc['Jan':'May', ['eggs', 'spam']]

       eggs  spam
month
Jan      47    17
Feb     110    31
Mar     221    72
Apr      77    20
May     132    52

In [16]:
data.iloc[[0,4,5], 0:2]

       eggs  salt
month
Jan      47  12.0
May     132   NaN
Jun     205  60.0

**Series versus 1-column DataFrame**

In [17]:
print(type(data['eggs']))
print(type(data[['eggs']])) #Better !

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>



---



---



---

# Filtering DataFrames

In [ ]:
data.salt>60

month
Jan    False
Feb    False
Mar     True
Apr     True
May    False
Jun    False
Name: salt, dtype: bool

In [ ]:
data[data.salt > 60]

       eggs  salt  spam
month
Mar     221  89.0    72
Apr      77  87.0    20

# Combining filters

In [ ]:
data[(data.salt >= 50) & (data.eggs < 200)] # Both conditions

       eggs  salt  spam
month
Feb     110  50.0    31
Apr      77  87.0    20

In [18]:
data[(data.salt >= 50) | (data.eggs < 200)] # Either condition

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

# DataFrames with zeros and NaNs

In [19]:
df2 = data.copy()
df2['bacon'] = [0, 0, 50, 60, 70, 80]

In [20]:
df2

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     221  89.0    72     50
Apr      77  87.0    20     60
May     132   NaN    52     70
Jun     205  60.0    55     80

In [21]:
data

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

In [22]:
df2.all() #columns with all nonzeros

eggs      True
salt      True
spam      True
bacon    False
dtype: bool

In [23]:
#Select columns with all nonzeros
df2.loc[:, df2.all()]

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  89.0    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

In [24]:
#Select columns with any nonzeros
#at least one value is nonzero
df2.loc[:, df2.any()]

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     221  89.0    72     50
Apr      77  87.0    20     60
May     132   NaN    52     70
Jun     205  60.0    55     80

In [25]:
#Select columns with any NaNs
df2.loc[:, df2.isnull().any()]

       salt
month
Jan    12.0
Feb    50.0
Mar    89.0
Apr    87.0
May     NaN
Jun    60.0

In [26]:
#Select columns without NaNs
df2.loc[:, df2.notnull().all()]

       eggs  spam  bacon
month
Jan      47    17      0
Feb     110    31      0
Mar     221    72     50
Apr      77    20     60
May     132    52     70
Jun     205    55     80

In [27]:
#Drop rows with any NaNs
df2.dropna(how='any')

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     221  89.0    72     50
Apr      77  87.0    20     60
Jun     205  60.0    55     80

In [ ]:
#Filtering a column based on another column
df2.eggs[df2.salt > 55]

month
Mar    221
Apr     77
Jun    205
Name: eggs, dtype: int64

In [28]:
#Modifying a column based on another
df2.eggs[df2.salt > 55] += 5
df2
#Be careful if you compile many times, the operation will be iterated too.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     226  89.0    72     50
Apr      82  87.0    20     60
May     132   NaN    52     70
Jun     210  60.0    55     80

In [29]:
df2

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     226  89.0    72     50
Apr      82  87.0    20     60
May     132   NaN    52     70
Jun     210  60.0    55     80

**DataFrame vectorized methods**

In [ ]:
df2.floordiv(12) # Convert to dozens unit

       eggs  salt  spam  bacon
month
Jan       3   1.0     1      0
Feb       9   4.0     2      0
Mar      19   7.0     6      4
Apr       7   7.0     1      5
May      11   NaN     4      5
Jun      18   5.0     4      6

**Defining columns using other columns**

In [ ]:
df2

       eggs  salt  spam  bacon
month
Jan      47  12.0    17      0
Feb     110  50.0    31      0
Mar     236  89.0    72     50
Apr      92  87.0    20     60
May     132   NaN    52     70
Jun     220  60.0    55     80

In [30]:
df2['salty_eggs'] = df2.salt + df2.eggs
df2

       eggs  salt  spam  bacon  salty_eggs
month
Jan      47  12.0    17      0        59.0
Feb     110  50.0    31      0       160.0
Mar     226  89.0    72     50       315.0
Apr      82  87.0    20     60       169.0
May     132   NaN    52     70         NaN
Jun     210  60.0    55     80       270.0

* Series: 1D array with Index
* DataFrames: 2D array with Series as columns

In [31]:
#Examples of series
import pandas as pd
prices = [10.70, 10.86, 10.74, 10.71, 10.79]
shares = pd.Series(prices)
print(shares)
print(type(shares))

0    10.70
1    10.86
2    10.74
3    10.71
4    10.79
dtype: float64
<class 'pandas.core.series.Series'>

In [32]:
#Creating an index

days = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri']
shares = pd.Series(prices, index=days)
print(shares)
#find the index
print(shares.index)

Mon     10.70
Tue     10.86
Wed     10.74
Thur    10.71
Fri     10.79
dtype: float64
Index(['Mon', 'Tue', 'Wed', 'Thur', 'Fri'], dtype='object')

In [33]:
#Modifying index name
shares.index.name = 'weekday'
print(shares)

weekday
Mon     10.70
Tue     10.86
Wed     10.74
Thur    10.71
Fri     10.79
dtype: float64

In [35]:
#Modifying index entries
shares.index[2] = 'Wednesday'
print(shares)
#TypeError: Index does not support mutable operations

TypeError: ignored

In [36]:
#Modifying all index entries

shares.index = ['Monday', 'Tuesday', 'Wednesday','Thursday', 'Friday']
print(shares)

Monday       10.70
Tuesday      10.86
Wednesday    10.74
Thursday     10.71
Friday       10.79
dtype: float64

# Exploration of dataframes:

In [37]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
data = pd.read_csv("unemployment_data_us.csv")

Saving unemployment_data_us.csv to unemployment_data_us.csv

In [38]:
#Exploring the dataframe
data.head()

   Year Month  Primary_School      Date  ...  Asian  Hispanic   Men  Women
0  2010   Jan            15.3  Jan-2010  ...    8.3      12.9  10.2    7.9
1  2011   Jan            14.3  Jan-2011  ...    6.8      12.3   9.0    7.9
2  2012   Jan            13.0  Jan-2012  ...    6.7      10.7   7.7    7.6
3  2013   Jan            12.0  Jan-2013  ...    6.4       9.7   7.5    7.2
4  2014   Jan             9.4  Jan-2014  ...    4.7       8.3   6.2    5.8

[5 rows x 13 columns]

In [39]:
data.shape

(132, 13)

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 132 non-null    int64
 1   Month                132 non-null    object
 2   Primary_School       123 non-null    float64
 3   Date                 132 non-null    object
 4   High_School          123 non-null    float64
 5   Associates_Degree    123 non-null    float64
 6   Professional_Degree  123 non-null    float64
 7   White                123 non-null    float64
 8   Black                123 non-null    float64
 9   Asian                123 non-null    float64
 10  Hispanic             123 non-null    float64
 11  Men                  123 non-null    float64
 12  Women                123 non-null    float64
dtypes: float64(10), int64(1), object(2)
memory usage: 13.5+ KB

In [41]:
data.columns

Index(['Year', 'Month', 'Primary_School', 'Date', 'High_School',
       'Associates_Degree', 'Professional_Degree', 'White', 'Black', 'Asian',
       'Hispanic', 'Men', 'Women'],
      dtype='object')

In [47]:
data.isna().sum().sum()

90

Combien y'a t-il de 0 dans le dataset:

In [58]:
import numpy
test=data.values==0
print(type(test))
print(test.shape)
print(numpy.count_nonzero(test))

<class 'numpy.ndarray'>
(132, 13)
0